version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/talkio
      - JWT_SECRET=your_jwt_secret
      - ENCRYPTION_KEY=your_encryption_key
    depends_on:
      - mongo
    networks:
      - talkio_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - talkio_network

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - talkio_network

networks:
  talkio_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
